Matrix A:
[[0 2]
 [2 3]]
Shift s: 1

Shifted Matrix B = (A - sI):
[[-1.  2.]
 [ 2.  2.]]
Inverse of Shifted Matrix B_inv = (A - sI)^-1:
[[-0.33333333  0.33333333]
 [ 0.33333333  0.16666667]]

Starting vector x0: [0.70710678 0.70710678]

--- Iterations ---
Iteration 1:
  Approx Eigenvalue (λ): 3.828427
  Approx Eigenvector (v): [8.93438494e-17 1.00000000e+00]
Iteration 2:
  Approx Eigenvalue (λ): 4.000000
  Approx Eigenvector (v): [1.  0.5]
Iteration 3:
  Approx Eigenvalue (λ): 3.400000
  Approx Eigenvector (v): [-0.4  1. ]
Iteration 4:
  Approx Eigenvalue (λ): 3.142857
  Approx Eigenvector (v): [1.         0.07142857]
Iteration 5:
  Approx Eigenvalue (λ): 3.896552
  Approx Eigenvector (v): [-0.89655172  1.        ]
Iteration 6:
  Approx Eigenvalue (λ): 2.581818
  Approx Eigenvector (v): [ 1.         -0.20909091]
Iteration 7:
  Approx Eigenvalue (λ): -1.481203
  Approx Eigenvector (v): [ 1.        -0.7406015]
Iteration 8:
  Approx Eigenvalue (λ): -0.723542
  Approx Eigenvector (v): [ 1.

(np.float64(-0.8732359494924486), array([ 1.        , -0.43661797]))